# Generated by Django 2.0.5 on 2018-05-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0004_auto_20180505_1113'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Resposta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('cont_respostas', models.IntegerField(default=0, verbose_name='Respostas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos', to='cursos.Curso', verbose_name='Curso')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='resposta',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='forum.Topico', verbose_name='Tópico'),
        ),
    ]
