# Generated by Django 2.0.4 on 2018-05-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_anuncio_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(blank=True, default=0, verbose_name='Número de ordem')),
                ('atividade', models.BooleanField(default=False, verbose_name='Vincular ao término da unidade?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='cursos.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['curso', 'ordem'],
                'get_latest_by': ['curso', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('link', models.TextField(blank=True, verbose_name='Link de acesso ao vídeo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='aulas/videos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='cursos.Aula', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('curso', 'ordem')},
        ),
    ]
