# Generated by Django 2.0.6 on 2018-06-04 00:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cursos', '0004_auto_20180505_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
