# Generated by Django 2.0.6 on 2018-06-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComplementar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='aulas/materiais_complementares')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complementares', to='cursos.Aula', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Material complementar',
                'verbose_name_plural': 'Materiais complementares',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='nome',
        ),
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default='Título', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
