# Generated by Django 2.0.6 on 2018-06-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20180604_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Alternativa incorreta',
                'verbose_name_plural': 'Alternativas incorretas',
                'ordering': ['questao'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Questão')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('alternativa_correta', models.TextField(verbose_name='Alternativa correta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='cursos.Aula')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['aula'],
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='videos_assistidos',
            field=models.ManyToManyField(to='cursos.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(blank=True, help_text='Insira aqui o link completo para o vídeo no YouTube', verbose_name='ID do vídeo no YouTube'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternativas_erradas', to='cursos.Questao'),
        ),
    ]
