# Generated by Django 2.0.6 on 2018-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20180614_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, help_text='Insira aqui o link completo para o vídeo no YouTube', max_length=150, verbose_name='ID do vídeo no YouTube'),
        ),
    ]
