# Generated by Django 2.0.6 on 2018-06-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20180615_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['?'], 'verbose_name': 'Alternativa incorreta', 'verbose_name_plural': 'Alternativas incorretas'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_correta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False, verbose_name='Correta?'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternativas', to='cursos.Questao'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=100),
        ),
    ]
