# Generated by Django 2.0.6 on 2018-06-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_auto_20180616_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['?'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
    ]
