# Generated by Django 2.0.6 on 2018-06-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_auto_20180616_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('alternativa_escolhida', models.CharField(blank=True, max_length=100, verbose_name='Alternativa selecionada')),
                ('acerto', models.BooleanField(default=False, verbose_name='Acertou')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='cursos.Inscricao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='cursos.Questao')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['inscricao'],
            },
        ),
    ]
