# Generated by Django 2.0.6 on 2018-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_resposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['aula', 'data_atualizacao'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['inscricao', 'data_atualizacao'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='videos_assistidos',
            field=models.ManyToManyField(blank=True, to='cursos.Video'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='alternativa_escolhida',
            field=models.CharField(max_length=100, verbose_name='Alternativa selecionada'),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('inscricao', 'questao')},
        ),
    ]
