# Generated by Django 2.0.6 on 2018-06-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20180617_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='keywords',
        ),
    ]
