# Generated by Django 2.0.6 on 2018-06-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_auto_20180623_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='nota',
            new_name='nota_questionario',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nota_curso',
            field=models.IntegerField(choices=[(1, 'Muito insatisfeito'), (2, 'Insatisfeito'), (3, 'Regular'), (4, 'Satisfeito'), (5, 'Muito satisfeito')], default=None, null=True, verbose_name='Nota do curso'),
        ),
    ]
