# Generated by Django 2.0.6 on 2018-06-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_auto_20180624_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='nota_questionario',
            field=models.FloatField(default=0, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='qtd_videos',
            field=models.FloatField(default=0, null=True, verbose_name='Vídeos Assistidos'),
        ),
    ]
